<?php

namespace covBundle\Repository;

/**
 * reservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function select_reservations($id_user){
    $querybuilder=$this->getEntityManager()->createQueryBuilder();
    $querybuilder->select('r')
    ->from('covBundle:reservation','r')
        ->where(" r.etat = 'en cours'")
        ->andWhere($querybuilder->expr()->orX($querybuilder->expr()->neq('r.passager_1',':passager'),$querybuilder->expr()->isNull('r.passager_1')))
        ->andWhere($querybuilder->expr()->orX($querybuilder->expr()->neq('r.passager2',':passager'),$querybuilder->expr()->isNull('r.passager2')))
        ->andWhere($querybuilder->expr()->orX($querybuilder->expr()->neq('r.passager3',':passager'),$querybuilder->expr()->isNull('r.passager3')))
        ->andWhere($querybuilder->expr()->orX($querybuilder->expr()->neq('r.passager4',':passager'),$querybuilder->expr()->isNull('r.passager4')))
        ->andWhere($querybuilder->expr()->neq('r.conducteur',':passager'));
     $querybuilder->setParameter('passager',$id_user);
        return $querybuilder->getQuery()->getResult();

    }
    public function mes_resrvations($id_user){
        $querybuilder=$this->getEntityManager()->createQueryBuilder();
        $querybuilder->select('r')
        ->from('covBundle:reservation','r')
            ->where("r.etat = 'en cours'")
            ->andWhere($querybuilder->expr()->orX($querybuilder->expr()->eq('r.passager_1',':passager'),$querybuilder->expr()->orX($querybuilder->expr()->eq('r.passager2',':passager'),$querybuilder->expr()->orX($querybuilder->expr()->eq('r.passager3',':passager'),$querybuilder->expr()->eq('r.passager4',':passager')))))
            ->andWhere($querybuilder->expr()->neq('r.conducteur',':passager'));
        $querybuilder->setParameter('passager',$id_user);
        return $querybuilder->getQuery()->getResult();

    }
}
